version: "3.8"

services:
  database:
    build: ./database
    ports:
      - "1433:1433"
    volumes:
      - data:/var/opt/mssql

  backend:
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"

volumes:
  data: