import { Iuser } from "../interfaces";


const dummyUsers:Iuser[] = [
    {
    firstname: "John",
    lastname: "Doe",
    id: "1234567890",
    email: "john.doe@example.com",
    username: "johndoe",
    location: "New York, USA",
    joinedDate: "2022-01-01",
    website: null,
    github: "johndoe",
    avatar: "https://example.com/avatar1.jpg",
    role: "admin"
    },
    {
    firstname: "Jane",
    lastname: "Smith",
    id: "0987654321",
    email: "jane.smith@example.com",
    username: "janesmith",
    location: "Los Angeles, USA",
    joinedDate: "2022-02-02",
    website: null,
    github: "janesmith",
    avatar: "https://example.com/avatar2.jpg",
    role: "user"
    },
    {
    firstname: "Michael",
    lastname: "Johnson",
    id: "4567890123",
    email: "michael.johnson@example.com",
    username: "michaeljohnson",
    location: "London, UK",
    joinedDate: "2022-03-03",
    website: null,
    github: "michaeljohnson",
    avatar: "https://example.com/avatar3.jpg",
    role: "user"
    },
    {
    firstname: "Emily",
    lastname: "Davis",
    id: "9876543210",
    email: "emily.davis@example.com",
    username: "emilydavis",
    location: "Sydney, Australia",
    joinedDate: "2022-04-04",
    website: null,
    github: "emilydavis",
    avatar: "https://example.com/avatar4.jpg",
    role: "user"
    },
    {
    firstname: "David",
    lastname: "Anderson",
    id: "5432109876",
    email: "david.anderson@example.com",
    username: "davidanderson",
    location: "Toronto, Canada",
    joinedDate: "2022-05-05",
    website: null,
    github: "davidanderson",
    avatar: "https://example.com/avatar5.jpg",
    role: "user"
    },
    {
    firstname: "Sarah",
    lastname: "Wilson",
    id: "1357924680",
    email: "sarah.wilson@example.com",
    username: "sarahwilson",
    location: "Berlin, Germany",
    joinedDate: "2022-06-06",
    website: null,
    github: "sarahwilson",
    avatar: "https://example.com/avatar6.jpg",
    role: "user"
    },
    {
    firstname: "Christopher",
    lastname: "Thompson",
    id: "8642097531",
    email: "christopher.thompson@example.com",
    username: "christopherthompson",
    location: "Paris, France",
    joinedDate: "2022-07-07",
    website: null,
    github: "christopherthompson",
    avatar: "https://example.com/avatar7.jpg",
    role: "user"
    },
    {
    firstname: "Olivia",
    lastname: "Martinez",
    id: "3141592653",
    email: "olivia.martinez@example.com",
    username: "oliviamartinez",
    location: "Madrid, Spain",
    joinedDate: "2022-08-08",
    website: null,
    github: "oliviamartinez",
    avatar: "https://example.com/avatar8.jpg",
    role: "user"
    },
    {
    firstname: "Ethan",
    lastname: "Hernandez",
    id: "2718281828",
    email: "ethan.hernandez@example.com",
    username: "ethanhernandez",
    location: "Rome, Italy",
    joinedDate: "2022-09-09",
    website: null,
    github: "ethanhernandez",
    avatar: "https://example.com/avatar9.jpg",
    role: "user"
    },
    {
    firstname: "Ava",
    lastname: "Moore",
    id: "9234567891",
    email: "ava.moore@example.com",
    username: "avamoore",
    location: "Tokyo, Japan",
    joinedDate: "2022-10-10",
    website: null,
    github: "avamoore",
    avatar: "https://example.com/avatar10.jpg",
    role: "user"
    },
    {
    firstname: "William",
    lastname: "Lee",
    id: "1928374650",
    email: "william.lee@example.com",
    username: "williamlee",
    location: "Seoul, South Korea",
    joinedDate: "2022-11-11",
    website: null,
    github: "williamlee",
    avatar: "https://example.com/avatar11.jpg",
    role: "user"
    },
    {
    firstname: "Sophia",
    lastname: "Clark",
    id: "8765432109",
    email: "sophia.clark@example.com",
    username: "sophiaclark",
    location: "Moscow, Russia",
    joinedDate: "2022-12-12",
    website: null,
    github: "sophiaclark",
    avatar: "https://example.com/avatar12.jpg",
    role: "user"
    },
    {
    firstname: "James",
    lastname: "Lewis",
    id: "5678901234",
    email: "james.lewis@example.com",
    username: "jameslewis",
    location: "Beijing, China",
    joinedDate: "2023-01-01",
    website: null,
    github: "jameslewis",
    avatar: "https://example.com/avatar13.jpg",
    role: "user"
    },
    {
    firstname: "Mia",
    lastname: "Young",
    id: "9876543211",
    email: "mia.young@example.com",
    username: "miayoung",
    location: "Mumbai, India",
    joinedDate: "2023-02-02",
    website: null,
    github: "miayoung",
    avatar: "https://example.com/avatar14.jpg",
    role: "user"
    },
    {
    firstname: "Benjamin",
    lastname: "Walker",
    id: "2468013579",
    email: "benjamin.walker@example.com",
    username: "benjaminwalker",
    location: "Sydney, Australia",
    joinedDate: "2023-03-03",
    website: null,
    github: "benjaminwalker",
    avatar: "https://example.com/avatar15.jpg",
    role: "user"
    },
    {
    firstname: "Charlotte",
    lastname: "Hall",
    id: "5432109876",
    email: "charlotte.hall@example.com",
    username: "charlottehall",
    location: "Toronto, Canada",
    joinedDate: "2023-04-04",
    website: null,
    github: "charlottehall",
    avatar: "https://example.com/avatar16.jpg",
    role: "user"
    },
    {
    firstname: "Daniel",
    lastname: "Turner",
    id: "8901234567",
    email: "daniel.turner@example.com",
    username: "danielturner",
    location: "London, UK",
    joinedDate: "2023-05-05",
    website: null,
    github: "danielturner",
    avatar: "https://example.com/avatar17.jpg",
    role: "user"
    },
    {
    firstname: "Harper",
    lastname: "Scott",
    id: "7654321098",
    email: "harper.scott@example.com",
    username: "harperscott",
    location: "Los Angeles, USA",
    joinedDate: "2023-06-06",
    website: null,
    github: "harperscott",
    avatar: "https://example.com/avatar18.jpg",
    role: "user"
    },
    {
    firstname: "Matthew",
    lastname: "Adams",
    id: "6543210987",
    email: "matthew.adams@example.com",
    username: "matthewadams",
    location: "New York, USA",
    joinedDate: "2023-07-07",
    website: null,
    github: "matthewadams",
    avatar: "https://example.com/avatar19.jpg",
    role: "user"
    },
    {
    firstname: "Amelia",
    lastname: "Hill",
    id: "4321098765",
    email: "amelia.hill@example.com",
    username: "ameliahill",
    location: "Paris, France",
    joinedDate: "2023-08-08",
    website: null,
    github: "ameliahill",
    avatar: "https://example.com/avatar20.jpg",
    role: "user"
    },
    {
    firstname: "Alexander",
    lastname: "Green",
    id: "2109876543",
    email: "alexander.green@example.com",
    username: "alexandergreen",
    location: "Madrid, Spain",
    joinedDate: "2023-09-09",
    website: null,
    github: "alexandergreen",
    avatar: "https://example.com/avatar21.jpg",
    role: "user"
    },
    {
    firstname: "Sofia",
    lastname: "Baker",
    id: "1098765432",
    email: "sofia.baker@example.com",
    username: "sofiabaker",
    location: "Berlin, Germany",
    joinedDate: "2023-10-10",
    website: null,
    github: "sofiabaker",
    avatar: "https://example.com/avatar22.jpg",
    role: "user"
    },
    {
    firstname: "Joseph",
    lastname: "Adams",
    id: "0987654321",
    email: "joseph.adams@example.com",
    username: "josephadams",
    location: "Rome, Italy",
    joinedDate: "2023-11-11",
    website: null,
    github: "josephadams",
    avatar: "https://example.com/avatar23.jpg",
    role: "user"
    },
    {
    firstname: "Victoria",
    lastname: "King",
    id: "9876543210",
    email: "victoria.king@example.com",
    username: "victoriaking",
    location: "Tokyo, Japan",
    joinedDate: "2023-12-12",
    website: null,
    github: "victoriaking",
    avatar: "https://example.com/avatar24.jpg",
    role: "user"
    },
    {
    firstname: "Oliver",
    lastname: "Young",
    id: "8765432109",
    email: "oliver.young@example.com",
    username: "oliveryoung",
    location: "Seoul, South Korea",
    joinedDate: "2024-01-01",
    website: null,
    github: "oliveryoung",
    avatar: "https://example.com/avatar25.jpg",
    role: "user"
    },
    {
    firstname: "Emma",
    lastname: "Carter",
    id: "7654321098",
    email: "emma.carter@example.com",
    username: "emmacarter",
    location: "Moscow, Russia",
    joinedDate: "2024-02-02",
    website: null,
    github: "emmacarter",
    avatar: "https://example.com/avatar26.jpg",
    role: "user"
    },
    {
    firstname: "Liam",
    lastname: "Mitchell",
    id: "6543210987",
    email: "liam.mitchell@example.com",
    username: "liammitchell",
    location: "Beijing, China",
    joinedDate: "2024-03-03",
    website: null,
    github: "liammitchell",
    avatar: "https://example.com/avatar27.jpg",
    role: "user"
    },
    {
    firstname: "Isabella",
    lastname: "Patel",
    id: "5432109876",
    email: "isabella.patel@example.com",
    username: "isabellapatel",
    location: "Mumbai, India",
    joinedDate: "2024-04-04",
    website: null,
    github: "isabellapatel",
    avatar: "https://example.com/avatar28.jpg",
    role: "user"
    },
    {
    firstname: "Henry",
    lastname: "Ramirez",
    id: "4321098765",
    email: "henry.ramirez@example.com",
    username: "henryramirez",
    location: "Sydney, Australia",
    joinedDate: "2024-05-05",
    website: null,
    github: "henryramirez",
    avatar: "https://example.com/avatar29.jpg",
    role: "user"
    },
    {
    firstname: "Ava",
    lastname: "Bailey",
    id: "3210987654",
    email: "ava.bailey@example.com",
    username: "avabailey",
    location: "Toronto, Canada",
    joinedDate: "2024-06-06",
    website: null,
    github: "avabailey",
    avatar: "https://example.com/avatar30.jpg",
    role: "user"
    }
  ]


export default dummyUsers